import { IBaseUOM } from './uom.interface';

// Base UoM master list
export const BASE_UOMS: IBaseUOM[] = [
  { label: 'BAGS', UQC: 'BAG' },
  { label: 'BALE', UQC: 'BAL' },
  { label: 'BUNDLES', UQC: 'BDL' },
  { label: 'BUCKLES', UQC: 'BKL' },
  { label: 'BILLIONS OF UNITS', UQC: 'BOU' },
  { label: 'BOX', UQC: 'BOX' },
  { label: 'BOTTLES', UQC: 'BTL' },
  { label: 'BUNCHES', UQC: 'BUN' },
  { label: 'CANS', UQC: 'CAN' },
  { label: 'CUBIC METER', UQC: 'CBM' },
  { label: 'CUBIC CENTIMETER', UQC: 'CCM' },
  { label: 'CENTIMETER', UQC: 'CMS' },
  { label: 'CARTONS', UQC: 'CTN' },
  { label: 'DOZEN', UQC: 'DOZ' },
  { label: 'DRUM', UQC: 'DRM' },
  { label: 'GREAT GROSS', UQC: 'GGR' },
  { label: 'GRAMS', UQC: 'GMS' },
  { label: 'GROSS', UQC: 'GRS' },
  { label: 'GROSS YARDS', UQC: 'GYD' },
  { label: 'KILOGRAMS', UQC: 'KGS' },
  { label: 'KILOLITER', UQC: 'KLR' },
  { label: 'KILOMETRE', UQC: 'KME' },
  { label: 'MILLILITRE', UQC: 'MLT' },
  { label: 'METERS', UQC: 'MTR' },
  { label: 'METRIC TON', UQC: 'MTS' },
  { label: 'NUMBERS', UQC: 'NOS' },
  { label: 'PACKS', UQC: 'PAC' },
  { label: 'PIECES', UQC: 'PCS' },
  { label: 'PAIRS', UQC: 'PRS' },
  { label: 'QUINTAL', UQC: 'QTL' },
  { label: 'ROLLS', UQC: 'ROL' },
  { label: 'SETS', UQC: 'SET' },
  { label: 'SQUARE FEET', UQC: 'SQF' },
  { label: 'SQUARE METERS', UQC: 'SQM' },
  { label: 'SQUARE YARDS', UQC: 'SQY' },
  { label: 'TABLETS', UQC: 'TBS' },
  { label: 'TEN GROSS', UQC: 'TGM' },
  { label: 'THOUSANDS', UQC: 'THD' },
  { label: 'TONNES', UQC: 'TON' },
  { label: 'TUBES', UQC: 'TUB' },
  { label: 'US GALLONS', UQC: 'UGS' },
  { label: 'UNITS', UQC: 'UNT' },
  { label: 'YARDS', UQC: 'YDS' },
  { label: 'OTHERS', UQC: 'OTH' },
];
